#!/bin/bash

# Exécuter les tests PHPUnit
echo "Running PHPUnit tests..."
./bin/phpunit

# Vérifier les erreurs de style de code avec PHP CodeSniffer
echo "Running PHP CodeSniffer..."
./vendor/bin/phpcs

# Analyser le code avec PHPStan
echo "Running PHPStan..."
./vendor/bin/phpstan analyse

if [ $? -ne 0 ]; then
  echo "Tests failed. Push aborted."
  exit 1
fi

echo "All tests passed. Proceeding with push."